num_iterations = 70
original_conformation = '4ake' # No need to add the suffix
target_conformation = '1ake' # No need to add the suffix
which_type_of_target = 'tsv'
combined_amplitude = 25
res_x = 0.5 # in nanometer
res_y = 0.5 # in nanometer
res_z = 0.64 # in Angstrom
size_x = 6.0 # This range represents half the size of the generated image in x-axis
size_y = 6.0 # This range represents half the size of the generated image in y-axis
first_mode = 1
last_mode = 16
mode_selection = 'slope' # ['slope', 'maxcc', 'maxcc_force_move']
how_many_threads = 8

# Whether to calculate the RMSD to a reference PDB file
calculate_rmsd_to_reference = 'yes' # ['yes', 'no']
file_name_of_reference_pdb = '1ake' # No need to add the suffix

# Shape of the probe
radius_of_probe = 2.0 # in nanometer
angle_of_probe = 10 # in degree
